import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Footer from "./components/Footer";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-white">
      <link rel="icon" href="https://static1.clickandboat.com/v1/o/img/favicon/CAB/favicon~0dd1ad09b5.ico" sizes="any"></link>
      <body className={"h-full"}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
